### ISSUE TITLE
Qt5 themes not configured

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/startdde#3] opened 2016-06-27 17:19 UTC
I'm test this in Deepin 15.2.

If use qt application, like qbittorrent this theme is uggly, but using this line solve the problem:

export QT_STYLE_OVERRIDE=gtk

Maybe one idea is add one /usr/bin/startdde shelscript, like startkde script for add some fixes like this.

Sorry for my bad english.

**Comment by snyh** [comment] 2016-07-12 00:47
What's the distro you use, deepin or arch ? 
the QT_STYLE_OVERRRIDE should be set.  (it has done in three years ago when the first version of dde released)

**Comment by bigbruno** [comment] 2016-07-14 03:25
Deepin 15.2.

**Comment by jouyouyun** [comment] 2017-07-31 06:26
@bigbruno can this bug reproduce in 15.4.1?

**Comment by felixonmars** [comment] 2017-07-31 06:36
@jouyouyun It's still in Arch. I cannot find where deepin set the envvar, any hints?

**Comment by jouyouyun** [comment] 2017-07-31 06:54
How to reproduce it?

**Comment by felixonmars** [comment] 2017-07-31 06:56
Just install DDE and run any Qt programs. The environment variable is not set so the UI is ugly.

**Comment by jouyouyun** [comment] 2017-07-31 07:11
screenshot?

**Comment by felixonmars** [comment] 2017-07-31 07:17
![2017-07-31-151651-ddde12](https://user-images.githubusercontent.com/1006477/28766695-5c70d8ba-7596-11e7-8c60-128ba79c1c00.png)

Program is kwrite. Default (left) vs Settings QT_STYLE_OVERRIDE=gtk2 manually (right)

**Comment by jouyouyun** [comment] 2017-07-31 07:41
Strangle! Only modify the file `$HOME/.config/Trolltech.conf` to set qt4 style 'GTK+'.

**Comment by felixonmars** [comment] 2017-07-31 08:10
@jouyouyun I believe that won't work with Qt 5 applications...

**Comment by jouyouyun** [comment] 2017-07-31 09:12
@zccrs 说是　libqt5libqgtk2 　做的，这个插件会让程序默认使用gtk2 style, gtk2 这个style中会根据gtk2的主题来绘制Qt的控件

**Comment by hualet** [comment] 2017-07-31 13:20
this one should be a duplicate of https://github.com/linuxdeepin/developer-center/issues/342#issuecomment-318972115 too

**Comment by felixonmars** [comment] 2017-07-31 15:44
I believe this should have been fixed in deepin-qt5integration 0.2.2-2. Please upgrade and test.

**Closed** 2017-08-16 09:45 UTC
